# Generated by Django 4.2.6 on 2023-10-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='inventario.pasta'),
        ),
    ]
