# Generated by Django 4.2.5 on 2023-11-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='09/11/2023', max_length=10),
        ),
    ]
