# Generated by Django 4.2.5 on 2023-11-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tamanho',
            field=models.FloatField(default=0.0),
        ),
    ]
