# Generated by Django 4.2.5 on 2023-11-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_file_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tamanho',
        ),
    ]
