# Generated by Django 4.2.5 on 2023-11-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_file_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extensao',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
