# Generated by Django 4.2.5 on 2023-11-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_file_extensao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='19/11/2023', max_length=10),
        ),
    ]
