# Generated by Django 4.2.3 on 2023-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='20/11/2023', max_length=10),
        ),
    ]
