# Generated by Django 4.2.7 on 2023-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='01/12/2023', max_length=10),
        ),
    ]
