# Generated by Django 5.0.2 on 2024-03-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='11/03/2024', max_length=10),
        ),
    ]
