# Generated by Django 5.0.6 on 2024-11-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='19/11/2024', max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='extensao',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
