# Generated by Django 5.0.6 on 2024-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='16/05/2024', max_length=10),
        ),
    ]
