# Generated by Django 5.0.6 on 2024-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='24/11/2024', max_length=10),
        ),
    ]
