# Generated by Django 5.0.6 on 2024-09-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='03/09/2024', max_length=10),
        ),
    ]
