# Generated by Django 5.0.6 on 2024-10-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_alter_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.CharField(default='13/10/2024', max_length=10),
        ),
    ]
