# Generated by Django 4.2.5 on 2023-11-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_grupo_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='publico',
            field=models.BooleanField(default=True),
        ),
    ]
