# Generated by Django 4.2.5 on 2023-11-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('chat', '0005_grupo_campanha_alter_grupo_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas_campanha', to='home.perfil')),
                ('para_campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_entrada', to='home.campanha')),
            ],
        ),
    ]
