# Generated by Django 4.2.7 on 2023-12-01 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_solicitacaoentrada_aceita'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='uuid_pers',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
