# Generated by Django 4.2.5 on 2023-11-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('chat', '0008_alter_grupo_campanha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='campanha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='home.campanha'),
        ),
    ]
