# Generated by Django 4.2.7 on 2023-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_grupo_uuid_pers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='uuid_pers',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
