# Generated by Django 4.2.5 on 2023-09-05 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemParanormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nex', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('nomePerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='DnD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('vida', models.IntegerField(null=True)),
                ('classe', models.CharField(max_length=100)),
                ('sub_classe', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('raca', models.CharField(max_length=100, null=True)),
                ('sub_raca', models.CharField(blank=True, max_length=100, null=True)),
                ('xp', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('forca', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('const', models.IntegerField(default=0)),
                ('inteli', models.IntegerField(default=0)),
                ('sab', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('inspiracao', models.BooleanField(default=False)),
                ('forcaSalvaguarda', models.BooleanField(default=False)),
                ('dexSalvaguarda', models.BooleanField(default=False)),
                ('constSalvaguarda', models.BooleanField(default=False)),
                ('intSalvaguarda', models.BooleanField(default=False)),
                ('sabSalvaguarda', models.BooleanField(default=False)),
                ('carismaSalvaguarda', models.BooleanField(default=False)),
                ('acrobacia', models.BooleanField(default=False)),
                ('adestrarAnimais', models.BooleanField(default=False)),
                ('arcana', models.BooleanField(default=False)),
                ('atletismo', models.BooleanField(default=False)),
                ('enganacao', models.BooleanField(default=False)),
                ('historia', models.BooleanField(default=False)),
                ('intuicao', models.BooleanField(default=False)),
                ('intimidacao', models.BooleanField(default=False)),
                ('investigacao', models.BooleanField(default=False)),
                ('medicina', models.BooleanField(default=False)),
                ('natureza', models.BooleanField(default=False)),
                ('percepcao', models.BooleanField(default=False)),
                ('atuacao', models.BooleanField(default=False)),
                ('persuasao', models.BooleanField(default=False)),
                ('religiao', models.BooleanField(default=False)),
                ('prestigitacao', models.BooleanField(default=False)),
                ('furtividade', models.BooleanField(default=False)),
                ('sobrevivencia', models.BooleanField(default=False)),
                ('proficienciasFerramentas', models.TextField(blank=True, null=True)),
                ('outrasProf_Linguagens', models.TextField(blank=True, null=True)),
                ('ca', models.IntegerField(default=0)),
                ('movi', models.FloatField(blank=True, null=True)),
                ('vidaTemp', models.IntegerField(blank=True, null=True)),
                ('hitDice', models.IntegerField(blank=True, null=True)),
                ('hitDiceType', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12')], default='d4', max_length=4)),
                ('deathSucess1', models.BooleanField(default=False)),
                ('deathSucess2', models.BooleanField(default=False)),
                ('deathSucess3', models.BooleanField(default=False)),
                ('deathFailure1', models.BooleanField(default=False)),
                ('deathFailure2', models.BooleanField(default=False)),
                ('deathFailure3', models.BooleanField(default=False)),
                ('pc', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('po', models.IntegerField(default=0)),
                ('pl', models.IntegerField(default=0)),
                ('inventario', models.TextField(blank=True, null=True)),
                ('personalidade', models.CharField(blank=True, max_length=350, null=True)),
                ('ideias', models.CharField(blank=True, max_length=350, null=True)),
                ('vinculos', models.CharField(blank=True, max_length=350, null=True)),
                ('fraquezas', models.CharField(blank=True, max_length=350, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('nomePerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('nome',)},
            },
        ),
    ]
