# Generated by Django 4.2.4 on 2023-09-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemparanormal',
            name='protecao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordemparanormal',
            name='resistencias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
