# Generated by Django 4.2.2 on 2023-09-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0002_alter_ordemparanormal_protecao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemparanormal',
            name='classe',
            field=models.CharField(choices=[('Combatente', 'Combatente'), ('Especialista', 'Especialista'), ('Ocultista', 'Ocultista')], default='Combatente', max_length=20),
        ),
    ]
