# Generated by Django 4.2.4 on 2023-09-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0003_alter_ordemparanormal_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemparanormal',
            name='acrobacia',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='acrobaciaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='adestramento',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='adestramentoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='alcance1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='alcance2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='alcance3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='alcance4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='alcance5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='alcance6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='artes',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='artesOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ataqueNome1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ataqueNome2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ataqueNome3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ataqueNome4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ataqueNome5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ataqueNome6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='atletismo',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='atletismoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='atualidades',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='atualidadesOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ciencias',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='cienciasOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='crime',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='crimeOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='critico1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='critico2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='critico3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='critico4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='critico5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='critico6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dano1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dano2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dano3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dano4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dano5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dano6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='diplomacia',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='diplomaciaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='enganacao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='enganacaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='especial1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='especial2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='especial3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='especial4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='especial5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='especial6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='fortitude',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='fortitudeOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='furtividade',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='furtividadeOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='iniciativa',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='iniciativaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='intimidacao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='intimidacaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='intuicao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='intuicaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='investigacao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='investigacaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='luta',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='lutaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='medicina',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='medicinaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ocultismo',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='ocultismoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='percepcao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='percepcaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='pilotagem',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='pilotagemOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='pontaria',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='pontariaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='profissao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='profissaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='reflexos',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='reflexosOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='religiao',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='religiaoOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='sobrevivencia',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='sobrevivenciaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tatica',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='taticaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tecnologia',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tecnologiaOutros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='teste1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='teste2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='teste3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='teste4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='teste5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='teste6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tipo1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tipo2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tipo3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tipo4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tipo5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='tipo6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='vontade',
            field=models.CharField(choices=[('Leigo', 'Leigo'), ('Treinado', 'Treinado'), ('Veterano', 'Veterano'), ('Especialista', 'Especialista')], default='Leigo', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='vontadeOutros',
            field=models.IntegerField(default=0),
        ),
    ]
