# Generated by Django 4.2.4 on 2023-09-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0003_dnd_acrobacia_dnd_adestraranimais_dnd_arcana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAtk', models.CharField(max_length=100)),
                ('bonus', models.IntegerField()),
                ('dadoTipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dnd',
            name='ataques',
            field=models.ManyToManyField(blank=True, to='meus_personagens.ataque'),
        ),
    ]
