# Generated by Django 4.2.4 on 2023-09-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0004_ordemparanormal_acrobacia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemparanormal',
            name='aparencia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='carga1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='carga2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='carga3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='carga4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='cargaAtual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='cargaMax',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='dt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='historico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='itens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='limiteCredito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='objetivo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='patente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='personalidade',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='pp',
            field=models.IntegerField(default=0),
        ),
    ]
