# Generated by Django 4.2.4 on 2023-09-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0004_ataque_dnd_ataques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnd',
            name='ataques',
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Ataque',
        ),
    ]
