# Generated by Django 4.2.4 on 2023-09-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0005_ordemparanormal_aparencia_ordemparanormal_carga1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemparanormal',
            name='cargaMax',
            field=models.IntegerField(default=0),
        ),
    ]
