# Generated by Django 4.2.4 on 2023-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0006_remove_dnd_bonusatk1_remove_dnd_bonusatk2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='bonusAtk5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='danoTipoAtk5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='nomeAtk5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
