# Generated by Django 4.2.4 on 2023-09-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0009_tormenta_acrobacia_tormenta_acrobaciamod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tormenta',
            name='TO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tormenta',
            name='TS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tormenta',
            name='carga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tormenta',
            name='equipamentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='atletismoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='For', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='atuacaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Car', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='conhecimentoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='curaMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Sab', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='diplomaciaMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Car', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='enganacaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Car', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='fortitudeMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Con', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='guerraMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='intimidacaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Car', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='intuicaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Sab', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='investigacaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='jogatinaMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Car', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='lutaMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='For', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='misticismoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='nobrezaMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='oficio1Mod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='oficio2Mod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Int', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='percepcaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Sab', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='religiaoMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Sab', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='sobrevivenciaMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Sab', max_length=3),
        ),
        migrations.AlterField(
            model_name='tormenta',
            name='vontadeMod',
            field=models.CharField(choices=[('For', 'For'), ('Des', 'Des'), ('Con', 'Con'), ('Int', 'Int'), ('Sab', 'Sab'), ('Car', 'Car')], default='Sab', max_length=3),
        ),
    ]
