# Generated by Django 4.2.4 on 2023-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0011_callofcthulhu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
