# Generated by Django 4.2.4 on 2023-09-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0012_alter_callofcthulhu_ataque1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque1Dano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque2Dano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque3Dano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='callofcthulhu',
            name='ataque4Dano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
