# Generated by Django 4.2.4 on 2023-09-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0013_alter_callofcthulhu_ataque1dano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnd',
            name='cantips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo1Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo1QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo2Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo2QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo3Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo3QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo4Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo4QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo5Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo5QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo6Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo6QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo7Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo7QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo8Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo8QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo9Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='circulo9QteMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='spellAttackBonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnd',
            name='spellCasting',
            field=models.CharField(choices=[('--', '--'), ('Força', 'Força'), ('Dextreza', 'Dextreza'), ('Constituição', 'Constituição'), ('Inteligência', 'Inteligência'), ('Sabedoria', 'Sabedoria'), ('Carisma', 'Carisma')], default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='dnd',
            name='spellDC',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
