# Generated by Django 4.2.2 on 2023-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0014_dnd_cantips_dnd_circulo1_dnd_circulo1qte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnd',
            name='carisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='const',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='dex',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='forca',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='int',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='sab',
            field=models.IntegerField(default=10),
        ),
    ]
