# Generated by Django 4.2.5 on 2023-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0015_alter_dnd_carisma_alter_dnd_const_alter_dnd_dex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callofcthulhu',
            name='foto',
            field=models.ImageField(default=1, upload_to='photos/coc1920/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnd',
            name='foto',
            field=models.ImageField(default=1, upload_to='photos/dnd5e/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='foto',
            field=models.ImageField(default=1, upload_to='photos/ordemParanormal/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tormenta',
            name='foto',
            field=models.ImageField(default=1, upload_to='photos/tormenta20/'),
            preserve_default=False,
        ),
    ]
