# Generated by Django 4.2.5 on 2023-09-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0016_callofcthulhu_foto_dnd_foto_ordemparanormal_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callofcthulhu',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='dnd',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='ordemparanormal',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='tormenta',
            name='foto',
        ),
    ]
