# Generated by Django 4.2.5 on 2023-09-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0017_remove_callofcthulhu_foto_remove_dnd_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnd',
            name='foto',
            field=models.ImageField(default=1, upload_to='meus_personagens/photos/dnd5e'),
            preserve_default=False,
        ),
    ]
