# Generated by Django 4.2.5 on 2023-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0019_alter_dnd_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='callofcthulhu',
            name='foto',
            field=models.ImageField(default=1, upload_to='images/coc1920'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemparanormal',
            name='foto',
            field=models.ImageField(default=1, upload_to='images/ordemParanormal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tormenta',
            name='foto',
            field=models.ImageField(default=1, upload_to='images/tormenta20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnd',
            name='foto',
            field=models.ImageField(upload_to='images/dnd5e'),
        ),
    ]
