# Generated by Django 5.0.6 on 2024-09-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meus_personagens', '0020_callofcthulhu_foto_ordemparanormal_foto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callofcthulhu',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dnd',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ordemparanormal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tormenta',
            unique_together=set(),
        ),
    ]
