# Generated by Django 5.0.6 on 2024-11-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('meus_personagens', '0021_alter_callofcthulhu_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maps/')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='PastaCriaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemParanormalCampanha',
            fields=[
                ('ordemparanormal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.ordemparanormal')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.ordemparanormal',),
        ),
        migrations.CreateModel(
            name='DnDCampanha',
            fields=[
                ('dnd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.dnd')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.dnd',),
        ),
        migrations.CreateModel(
            name='CallOfCthulhuCampanha',
            fields=[
                ('callofcthulhu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.callofcthulhu')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.callofcthulhu',),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='tokens/')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.map')),
            ],
        ),
        migrations.CreateModel(
            name='TormentaCampanha',
            fields=[
                ('tormenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.tormenta')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.tormenta',),
        ),
    ]
