# Generated by Django 5.0.6 on 2024-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='position_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='position_y',
            field=models.FloatField(default=0),
        ),
    ]
