# Generated by Django 5.0.6 on 2024-07-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('tabletop', '0002_map_token_delete_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='campanha_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.campanha'),
            preserve_default=False,
        ),
    ]
