# Generated by Django 5.0.6 on 2024-07-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabletop', '0003_map_campanha_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='background_image',
            new_name='image',
        ),
    ]
