# Generated by Django 5.0.6 on 2024-09-22 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('tabletop', '0004_rename_background_image_map_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='pastaCriaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
        ),
    ]
