# Generated by Django 5.0.6 on 2024-09-22 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('meus_personagens', '0021_alter_callofcthulhu_unique_together_and_more'),
        ('tabletop', '0005_pastacriaturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TormentaCampanha',
            fields=[
                ('tormenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.tormenta')),
                ('id_campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.tormenta',),
        ),
    ]
