# Generated by Django 5.0.6 on 2024-09-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabletop', '0006_tormentacampanha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tormentacampanha',
            old_name='id_campanha',
            new_name='campanha_id',
        ),
    ]
