# Generated by Django 5.0.6 on 2024-09-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campanha_fotocampanha_alter_perfil_fotoconta'),
        ('meus_personagens', '0021_alter_callofcthulhu_unique_together_and_more'),
        ('tabletop', '0007_rename_id_campanha_tormentacampanha_campanha_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOfCthulhuCampanha',
            fields=[
                ('callofcthulhu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.callofcthulhu')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.callofcthulhu',),
        ),
        migrations.CreateModel(
            name='DnDCampanha',
            fields=[
                ('dnd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.dnd')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.dnd',),
        ),
        migrations.CreateModel(
            name='OrdemParanormalCampanha',
            fields=[
                ('ordemparanormal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meus_personagens.ordemparanormal')),
                ('campanha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campanha')),
            ],
            options={
                'abstract': False,
            },
            bases=('meus_personagens.ordemparanormal',),
        ),
    ]
