# Generated by Django 5.0.6 on 2024-09-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletop', '0008_callofcthulhucampanha_dndcampanha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callofcthulhucampanha',
            name='pasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dndcampanha',
            name='pasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemparanormalcampanha',
            name='pasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tormentacampanha',
            name='pasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tabletop.pastacriaturas'),
            preserve_default=False,
        ),
    ]
