# Generated by Django 4.2.3 on 2023-07-19 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoConta', models.ImageField(upload_to='static/img/fotoUser')),
                ('tipo_sessao', models.CharField(blank=True, choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=20)),
                ('tipo_player', models.CharField(blank=True, choices=[('Mestre', 'Mestre'), ('Jogador', 'Jogador'), ('Ambos', 'Ambos')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('sistema_rpg', models.CharField(blank=True, choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Tormenta20', 'Tormenta20'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Call of Cthulhu', 'Call of Cthulhu'), ('Outros', 'Outros')], max_length=20)),
                ('nomePerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCampanha', models.CharField(max_length=52)),
                ('sistemaCampanha', models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Tormenta20', 'Tormenta20'), ('Call of Cthulu', 'Call of Cthulu'), ('Outro', 'Outro')], max_length=100)),
                ('descricaoCampanha', models.TextField(max_length=256)),
                ('fotoCampanha', models.ImageField(upload_to='static/img/FotoCampanha/')),
                ('ambienteCampanha', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=100)),
                ('numeroJogadores', models.IntegerField()),
                ('diasSessao', models.CharField(max_length=52)),
                ('generoRPG', models.CharField(choices=[('Aventura', 'Aventura'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Fantasia', 'Fantasia'), ('Histórico', 'Histórico'), ('Mistério', 'Mistério'), ('Suspense', 'Suspense'), ('Terror', 'Terror')], max_length=100)),
                ('nomeMestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
