# Generated by Django 4.2.3 on 2023-07-10 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCampanha', models.CharField(max_length=52)),
                ('sistemaCampanha', models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Tormenta20', 'Tormenta20'), ('Call of Cthulu', 'Call of Cthulu'), ('Outro', 'Outro')], max_length=100)),
                ('descricaoCampanha', models.CharField(max_length=256)),
                ('fotoCampanha', models.ImageField(upload_to='img/FotoCampanha/')),
                ('ambienteCampanha', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=100)),
                ('numeroJogadores', models.IntegerField()),
                ('diasSessao', models.CharField(max_length=52)),
                ('generoRPG', models.CharField(choices=[('Aventura', 'Aventura'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Fantasia', 'Fantasia'), ('Histórico', 'Histórico'), ('Mistério', 'Mistério'), ('Suspense', 'Suspense'), ('Terror', 'Terror')], max_length=100)),
                ('nomeMestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
