# Generated by Django 4.2.5 on 2023-09-05 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fotoConta', models.ImageField(null=True, upload_to='static/img/fotoUser')),
                ('tipo_sessao', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=20, null=True)),
                ('tipo_player', models.CharField(choices=[('Mestre', 'Mestre'), ('Jogador', 'Jogador'), ('Ambos', 'Ambos')], max_length=20, null=True)),
                ('descricao', models.TextField(max_length=256, null=True)),
                ('sistema_rpg', models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Tormenta20', 'Tormenta20'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Call of Cthulhu', 'Call of Cthulhu'), ('Outros', 'Outros')], max_length=20, null=True)),
                ('idade', models.IntegerField(null=True)),
                ('nomePerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCampanha', models.CharField(max_length=52, null=True)),
                ('sistemaCampanha', models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Tormenta20', 'Tormenta20'), ('Call of Cthulu', 'Call of Cthulu'), ('Outro', 'Outro')], max_length=100, null=True)),
                ('descricaoCampanha', models.TextField(max_length=256, null=True)),
                ('fotoCampanha', models.ImageField(null=True, upload_to='static/img/FotoCampanha/')),
                ('ambienteCampanha', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=100, null=True)),
                ('numeroJogadores', models.IntegerField(null=True)),
                ('diasSessao', models.CharField(max_length=52, null=True)),
                ('generoRPG', models.CharField(choices=[('Aventura', 'Aventura'), ('Fantasia', 'Fantasia'), ('Histórico', 'Histórico'), ('Mistério', 'Mistério'), ('Suspense', 'Suspense'), ('Terror', 'Terror')], max_length=100, null=True)),
                ('nomeMestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.perfil')),
            ],
        ),
    ]
