# Generated by Django 4.2.3 on 2023-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sistema_rpg',
            field=models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Tormenta20', 'Tormenta20'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Call of Cthulhu', 'Call of Cthulhu'), ('Outros', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_player',
            field=models.CharField(choices=[('Mestre', 'Mestre'), ('Jogador', 'Jogador'), ('Ambos', 'Ambos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_sessao',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=20),
        ),
    ]
