# Generated by Django 4.2.3 on 2023-09-20 15:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoConta',
            field=models.ImageField(upload_to='static/img/fotoUser'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
