# Generated by Django 4.2.6 on 2023-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_perfil_fotoconta_alter_perfil_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='fotoCampanha',
            field=models.ImageField(null=True, upload_to='images/FotoCampanha/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fotoConta',
            field=models.ImageField(upload_to='images/profilePictures'),
        ),
    ]
