# Generated by Django 4.2.3 on 2023-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_perfil_descricao_alter_perfil_sistema_rpg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
