# Generated by Django 4.2.4 on 2023-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_perfil_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='generoRPG',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Fantasia', 'Fantasia'), ('Histórico', 'Histórico'), ('Mistério', 'Mistério'), ('Suspense', 'Suspense'), ('Terror', 'Terror')], max_length=100),
        ),
    ]
