# Generated by Django 4.2.4 on 2023-08-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_campanha_generorpg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='ambienteCampanha',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='descricaoCampanha',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='diasSessao',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='fotoCampanha',
            field=models.ImageField(null=True, upload_to='static/img/FotoCampanha/'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='generoRPG',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Fantasia', 'Fantasia'), ('Histórico', 'Histórico'), ('Mistério', 'Mistério'), ('Suspense', 'Suspense'), ('Terror', 'Terror')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='nomeCampanha',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='numeroJogadores',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='sistemaCampanha',
            field=models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Tormenta20', 'Tormenta20'), ('Call of Cthulu', 'Call of Cthulu'), ('Outro', 'Outro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fotoConta',
            field=models.ImageField(null=True, upload_to='static/img/fotoUser'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sistema_rpg',
            field=models.CharField(choices=[('Dungeons & Dragons', 'Dungeons & Dragons'), ('Tormenta20', 'Tormenta20'), ('Ordem Paranormal', 'Ordem Paranormal'), ('Call of Cthulhu', 'Call of Cthulhu'), ('Outros', 'Outros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_player',
            field=models.CharField(choices=[('Mestre', 'Mestre'), ('Jogador', 'Jogador'), ('Ambos', 'Ambos')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_sessao',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial')], max_length=20, null=True),
        ),
    ]
