# Generated by Django 4.2.5 on 2023-10-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistAmizade', '0003_amizade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amizade',
        ),
    ]
