# Generated by Django 4.2.5 on 2023-10-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistAmizade', '0005_amigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='data_criacao',
        ),
    ]
