# Generated by Django 4.2.5 on 2023-11-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistAmizade', '0007_amigo_data_criacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitacaoamizade',
            unique_together=set(),
        ),
    ]
