# Generated by Django 4.2.7 on 2023-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistAmizade', '0009_amigo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='slug',
            field=models.SlugField(default=None, max_length=255),
        ),
    ]
