# Generated by Django 4.2.7 on 2023-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistAmizade', '0011_amigo_fotoconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='fotoConta',
            field=models.FileField(default='Indefinido', max_length=200, upload_to=''),
        ),
    ]
