# Generated by Django 4.2.7 on 2023-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistAmizade', '0012_alter_amigo_fotoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='nomeAmigo',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
